// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:projectid: rest-client-java
:page-layout: guide
:page-duration: 25 minutes
:page-releasedate: 2018-06-01
:page-description: Learn how to consume a RESTful web service
:page-tags: ['REST', 'Client', 'Java', 'JAX-RS', 'JSON-P', 'JSON-B']
:page-related-guides: ['rest-intro', 'rest-client-angularjs']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Consuming a RESTful web service

Explore how to access a simple RESTful web service and consume its resources in Java
using JSON-B and JSON-P.

// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

You will learn how to access a REST service, serialize a Java object that contains a
list of artists and their albums, and use two different approaches to deserialize
the returned JSON resources. The first approach consists of using the JSON-B API
to directly convert JSON messages into Java objects.  The second approach consists of
using the JSON-P API to process the JSON.

The REST service that provides the artists and albums resources has already been written
for you and is accessible at:

[source, role="no_copy"]
----
http://localhost:9080/artists
----

Which responds with the following JSON:

[source, json, role="no_copy"]
----
include::finish/src/resources/artists.json[]
----

You will implement the following two endpoints using the two deserialization approaches:

* `.../artists/total` to return the total number of artists in the JSON
* `.../artists/total/<artist>` to return the total number of albums in the JSON
for the particular artist

If you are interested in learning more about REST services and how you can write them, read
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Starting the service
// =================================================================================================

== Starting the service

If you want to start the REST service, run the Maven `install` and `liberty:start-server` goals from
the `start` directory:

[source, role="no_copy"]
----
mvn clean install
mvn liberty:start-server
----

When the server is running, you can find your service at:

* `http://localhost:9080/artists`


// =================================================================================================
// Guide
// =================================================================================================
== POJOs

To deserialize a JSON message, start with creating Plain Old Java Objects (POJOs) that represent what
is in the JSON and whose instance members map to the keys in the JSON.

For the purpose of this guide, you are given two POJOs: `Artist` and `Album`. The `Artist` object has
two instance members `name` and `albums`, which map to the artist name and the collection of the albums
they have written. The `Album` object represents a single object within the album collection, and
contains three instance members `title`, `artist`, and `ntracks`, which map to the album title, the
artist who wrote the album, and the number of tracks the album contains.

`start/src/main/java/io/openliberty/guides/consumingrest/model/Artist.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/model/Artist.java[tags=!comment]
----

`start/src/main/java/io/openliberty/guides/consumingrest/model/Album.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/model/Album.java[tags=!comment]
----

== Differences between JSON-B and JSON-P

With JSON-B you directly serialize and deserialize POJOs. This API gives you a
variety of options for working with JSON resources.

In contrast, you need to use helper methods with JSON-P to process the JSON response.
This tactic is more straightforward, but it can be cumbersome with more complex classes.

JSON-B is built on top of the existing JSON-P API. JSON-B can do everything that JSON-P can do
and allows for more customization for serializing and deserializing. For
more information on JSON-B and how to serialize POJOs into JSON strings, refer to the
http://json-b.net/users-guide.html[JSON Binding 1.0 Users Guide].

=== Using JSON-B

JSON-B is a feature introduced with Java EE 8 and strengthens Java support for JSON.
By default, JSON-B requires a public default no-argument constructor for deserialization.

The JSON-B engine includes a set of default mapping rules, which can be run without
any customization annotations or custom configuration. In some instances, you might
find it useful to deserialize a JSON message with only certain fields, specific
field names, or classes with custom constructors. In these cases,
annotations are necessary and recommended:

* The `@JsonbProperty` annotation to map JSON keys to class instance members and vice versa.
Without the use of this annotation, JSON-B will attempt to do POJO mapping, matching the keys in
the JSON to the class instance members by name. If these names do not match, then getters and setters
are matched to JSON keys and the instance members are set explicitly. If the getter and setter
signatures do not match any key names, then deserialization fails. The Artist POJO
does not require this annotation because all instance members match the JSON keys by name.

* The `@JsonbCreator` and `@JsonbProperty` annotations to annotate a custom constructor.
This annotation is required for proper parameter substitution when a custom constructor is used.

* The `@JsonbTransient` annotation to define an object property that does not map to a JSON
property. While the use of this annotation is good practice, it is only necessary for serialization.

For more information on customization with JSON-B, see the
http://json-b.net/users-guide.html[JSON Binding 1.0 Users Guide].

// =================================================================================================
// Consuming REST resource
// =================================================================================================

== Consuming the REST resource

Write a simple `Consumer` class that consumes the artist JSON using both JSON-B and JSON-P.

`start/src/test/java/io/openliberty/guides/consumingrest/Consumer.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/Consumer.java[tags=!comment;!class]
----

=== Processing JSON using JSON-B

JSON-B is a Java API that is used to serialize Java objects to JSON messages and vice versa.

To include the JSON-B provider in your project, add the following dependency to your `pom.xml`
file, which is already done for you:

[source, xml, role="no_copy"]
----
<dependency>
   <groupId>javax.json.bind</groupId>
   <artifactId>javax.json.bind-api</artifactId>
   <version>1.0</version>
</dependency>
----

Use JSON-B in the `Consumer` class to write the method for consuming the REST service:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/Consumer.java[tags=consumeWithJsonb]
----

This method makes a `GET` request to the running artist service and retrieves the JSON.

To bind the JSON into an `Artist` array, use the `Artist[]` entity type in the `readEntity` call:

[source, java, indent = 0, role="no_copy"]
----
Artist[] artists = response.readEntity(Artist[].class);
----

Write the `getJsonString` and `getTotalAlbums` methods in the `ArtistResource` class. The `getTotalAlbums`
method uses JSON-B to return the total number of albums present in the JSON for a particular artist. The
method returns -1 if this artist does not exist. The `getJsonString` method returns the JSON as
a string that will be used later for testing.

`start/src/main/java/io/openliberty/guides/consumingrest/service/ArtistResource.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/service/ArtistResource.java[tags=getJsonString]
include::finish/src/main/java/io/openliberty/guides/consumingrest/service/ArtistResource.java[tags=getTotalAlbums]
----

=== Processing JSON using JSON-P

Write the method for consuming the REST service using JSON-P in the `Consumer` class:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/Consumer.java[tags=consumeWithJsonp]
----

Write the `collectArtists` and `collectAlbums` helpers. These methods will parse the JSON and
collect its objects into individual POJOs.  Notice that the you can use the custom constructors
to create instances of `Artist` and `Album`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/Consumer.java[tags=collectArtists;collectAlbums]
----

Write the `getTotalArtists` method in the `ArtistResource` class. This method will use the JSON-P
approach to return the total number of artists present in the JSON.

`start/src/main/java/io/openliberty/guides/consumingrest/service/ArtistResource.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/service/ArtistResource.java[tags=getTotalArtists]
----

The methods that you created in the `Consumer` class can be written directly in the
`ArtistResource` class. However, if you are consuming a REST resource from a third
party service, you can separate your `GET` and `POST` requests from your data consumption.

// =================================================================================================
// Testing deserialization
// =================================================================================================

== Testing deserialization

Create a test class, `start/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java`.

Maven finds and executes all tests under `it/` and each test method must be marked with the `@Test` annotation.

You can use the `@BeforeClass` and `@AfterClass` annotations to perform any one time setup and teardown
tasks before and after all of your tests execute, as well as the `@Before` and `@After` annotations
to do the same but for each individual test case.

[source, java]
----
include::finish/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java[tags=**;!comment;!tests]
----

=== Testing the binding process
For your test classes to have access to JSON-B, add the following dependency to your
`pom.xml` file, which is already done for you:

[source, xml]
----
<dependency>
    <groupId>org.eclipse</groupId>
    <artifactId>yasson</artifactId>
    <version>1.0.1</version>
    <scope>test</scope>
</dependency>
----

Write the `testArtistDeserialization` test case. This test checks that `Artist` instances created from
the REST data and those that are hardcoded perform the same.

[source, java, indent = 0]
----
include::finish/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java[tags=testArtistDeserialization]
----

=== Testing the processing with JSON-B

Write the `testAlbumCount` test case. This test checks that deserialization with JSON-B was done correctly
and that the correct number of albums is returned for each artist in the JSON.

[source, java, indent = 0]
----
include::finish/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java[tags=testAlbumCount]
----

Write the `testAlbumCountForUnknownArtist` test case. This test case is similar to `testAlbumCount`
but instead checks an artist that does not exist in the JSON.

[source, java, indent = 0]
----
include::finish/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java[tags=testAlbumCountForUnknownArtist]
----

=== Testing the processing with JSON-P

Write the `testArtistCount` test case. This test checks that deserialization with JSON-P was done correctly
and that the correct number of artists is returned.

[source, java, indent = 0]
----
include::finish/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java[tags=testArtistCount]
----

Write the `assertResponse` helper method that asserts that the response code you receive is valid (200):

[source, java, indent = 0]
----
include::finish/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java[tags=assertResponse]
----

=== Running the tests

To rebuild and run the tests, navigate to the `start` directory and run `mvn clean install` from the
command line.

[source, role="no_copy"]
----
# If server is still running from previous steps, stop it first
mvn liberty:stop-server

# Then execute
mvn clean install
----

It might take some time before the tests are executed. If the tests pass, you see the following
output:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.consumingrest.ConsumingRestTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.59 sec - in it.io.openliberty.guides.consumingrest.ConsumingRestTest

Results :

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0

----

== Great work! You're done!

You have just accessed a simple RESTful web service and consumed its resources using JSON-B and JSON-P.


include::{common-includes}/finish.adoc[]
