// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:projectid: rest-client-java
:page-layout: guide
:page-duration: 20 minutes
:page-description: Learn how to consume a RESTful web service
:page-tags: ['REST', 'Client', 'Java', 'JAX-RS', 'JSON-P']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Consuming a RESTful web service

Explore how to access a simple RESTful web service and consume its resources in Java.


// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

You will learn how to access a REST service and deserialize the returned JSON resources containing a
list of artists and their albums using two different approaches. The first approach consists of using
the JSON-P API to process the JSON. The second approach focuses on using a JSON binding library like
Jackson to convert JSON messages into Java objects directly.

The REST service that provides the artists and albums resources has already been written for you and
is accessible at:

[source, role="no_copy"]
----
http://localhost:9080/artists
----

Which responds with the following JSON:

[source, json, role="no_copy"]
----
include::finish/src/resources/artists.json[]
----

You will implement the following two endpoints using the two deserialization approaches:

* `.../artists/total` to return the total number of artists in the JSON
* `.../artists/total/<artist>` to return the total number of albums in the JSON
for the particular artist

If you are interested in learning more about REST services and how you can write them, read
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Starting the service
// =================================================================================================

== Starting the service

If you want to start the REST service, run the Maven `install` and `liberty:start-server` goals from
the `start` directory:

[source, role="no_copy"]
----
mvn clean install
mvn liberty:start-server
----

When the server is running, you can find your service at:

* `http://localhost:9080/artists`


// =================================================================================================
// Guide
// =================================================================================================

== POJOs

To deserialize a JSON message, start with creating Plain Old Java Objects (POJO) that represent what
is in the JSON and whose instance members map to the keys in the JSON.

For the purpose of this guide, you are given two POJOs: `Artist` and `Album`. The `Artist` object has
two instance members `name` and `albums`, which map to the artist name and the collection of the albums
they have written. The `Album` object represents a single object within the album collection, and
contains three instance members `title`, `artist`, and `ntracks`, which map to the album title, the
artist who wrote the album, and the number of tracks the album contains.

`start/src/main/java/io/openliberty/guides/consumingrest/model/Artist.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/model/Artist.java[tags=!comment]
----

`start/src/main/java/io/openliberty/guides/consumingrest/model/Album.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/model/Album.java[tags=!comment]
----

=== Using Jackson

In the case of using Jackson for JSON binding, a few restrictions are applicable to these objects,
they:

* Cannot have a constructor unless it is empty.
* Must contain the same number of instance members as there are keys in the target JSON.

While Jackson annotations are not always necessary, they are considered good practice when used:

* The `@JsonProperty` annotation is used to map JSON keys to class instance members and vice versa.
Without the use of this annotation, Jackson will attempt to do POJO mapping, matching the keys in
the JSON to the class instance members by name. If these names do not match, then getters and setters
are matched to JSON keys and the instance members are set explicitly. If the getter and setter
signatures do not match any key names, then deserialization fails. Note that the `Artist` POJO,
does not require this annotation since all instance members match the JSON keys by name.

* The `@JsonIgnore` annotation is used to define an object property that does not map to any JSON
property. While the use of this annotation is good practice, it is only necessary for serialization.


// =================================================================================================
// Consuming REST resource
// =================================================================================================

== Consuming the REST resource

Write a simple `Consumer` class that consumes the artist JSON using both JSON-P and Jackson.

`start/src/test/java/io/openliberty/guides/consumingrest/Consumer.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/Consumer.java[tags=!comment;!class]
----

=== Processing JSON using JSON-P

Write the method for consuming the REST service using JSON-P in the `Consumer` class:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/Consumer.java[tags=consumeWithJsonp]
----

This method makes a `GET` request to the running artist service and retrieves the JSON.

Write the `collectArtists` and `collectAlbums` helpers. These methods will parse that JSON and
collect its objects into individual POJOs:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/Consumer.java[tags=collectArtists;collectAlbums]
----

Write the `getTotalArtists` method in the `ArtistResource` class. This method will use the JSON-P
approach to return the total number of artists present in the JSON.

`start/src/main/java/io/openliberty/guides/consumingrest/service/ArtistResource.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/service/ArtistResource.java[tags=getTotalArtists]
----

=== Using a JSON binding library

Jackson is a JSON library for Java that is used to serialize Java objects to JSON messages and vice versa.

To include the Jackson JAX-RS JSON provider in your project, add the following dependency to your `pom.xml`,
which has been done for you:

[source, xml]
----
<dependency>
  <groupId>com.fasterxml.jackson.jaxrs</groupId>
  <artifactId>jackson-jaxrs-json-provider</artifactId>
  <version>2.9.0</version>
</dependency>
----

Write the method for consuming the REST service using Jackson's JSON binding in the `Consumer` class:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/Consumer.java[tags=consumeWithJackson]
----

To use Jackson's JAX-RS JSON provider, you must explicitly register it like the following line since
automatic discovery and registration are not available in the JAX-RS client API:

[source, java]
----
client.register(JacksonJsonProvider.class);
----

To bind the JSON into an `Artist` array, use the `Artist[]` entity type in the `readEntity` call:

[source, java, indent = 0]
----
Artist[] artists = response.readEntity(Artist[].class);
----

Write the `getTotalAlbums` method in the `ArtistResource` class. This method will return the total
number of albums present in the JSON for a particular artist and -1 if this artist does not exist.

`start/src/main/java/io/openliberty/guides/consumingrest/service/ArtistResource.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/consumingrest/service/ArtistResource.java[tags=getTotalAlbums]
----


// =================================================================================================
// Testing deserialization
// =================================================================================================

== Testing deserialization

Create a test class, `start/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java`.

Maven finds and executes all tests under `it/` and each test method must be marked with the `@Test` annotation.

You can use the `@BeforeClass` and `@AfterClass` annotations to perform any one time setup and teardown
tasks before and after all of your tests execute, as well as the `@Before` and `@After` annotations
to do the same but for each individual test case.

[source, java]
----
include::finish/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java[tags=**;!comment;!tests]
----

You can find more detailed explanations on how to define your own system properties and how to access
them via the `System.getProperty` call in the
https://openliberty.io/guides/microprofile-intro.html[MicroProfile guide].

=== Testing the processing with JSON-P

Write the `testArtistCount` test case. This test checks that deserialization with JSON-P was done correctly
and that the correct number of artist is returned.

[source, java, indent = 0]
----
include::finish/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java[tags=testArtistCount]
----

Write the `assertResponse` helper method that asserts that the response code you receive is valid (200):

[source, java, indent = 0]
----
include::finish/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java[tags=assertResponse]
----

=== Testing JSON binding with Jackson

Write the `testAlbumCount` test case. This test checks that deserialization with Jackson was done correctly
and that the correct number of albums is returned for each artist in the JSON.

[source, java, indent = 0]
----
include::finish/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java[tags=testAlbumCount]
----

Write the `testAlbumCountForUnknownArtist` test case. This test case is similar to `testAlbumCount`
but instead checks an artist that does not exist in the JSON.

[source, java, indent = 0]
----
include::finish/src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java[tags=testAlbumCountForUnknownArtist]
----

=== Running the tests

To rebuild and run the tests, navigate to the `start` directory and run `mvn clean install` from the
command line.

[source, role="no_copy"]
----
# If server is still running from previous steps, stop it first
mvn liberty:stop-server

# Then execute
mvn clean install
----

It might take some time before the tests are executed. If the tests pass, you see the following
output:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.consumingrest.ConsumingRestTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.957 sec - in it.io.openliberty.guides.consumingrest.ConsumingRestTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----


== Great work! You're done!

You have just accessed a simple RESTful web service and consumed its resources using JSON-P and Jackson.


include::{common-includes}/finish.adoc[]
